# PyTorch: Evaluating

https://github.com/pytorch/examples/tree/master/mnist

In [1]:
import os
from glob import glob

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms

import numpy as np

In [2]:
seed = 1

lr = 0.001
momentum = 0.5

batch_size = 64
test_batch_size = 64

epochs = 1
no_cuda = False
log_interval = 100

# Model

In [3]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5, 1)
        self.conv2 = nn.Conv2d(20, 50, 5, 1)
        self.fc1 = nn.Linear(4*4*50, 500)
        self.fc2 = nn.Linear(500, 10)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2, 2)
        x = x.view(-1, 4*4*50)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)

# Preprocess

In [4]:
datasets.MNIST('../dataset', train=True, download=True,
               transform=transforms.Compose([
                   transforms.ToTensor(),
                   transforms.Normalize((0.1307,), (0.3081,))
               ]))

100.1%

Extracting ../dataset\MNIST\raw\train-images-idx3-ubyte.gz to ../dataset\MNIST\raw


113.5%

Extracting ../dataset\MNIST\raw\train-labels-idx1-ubyte.gz to ../dataset\MNIST\raw


100.4%

Extracting ../dataset\MNIST\raw\t10k-images-idx3-ubyte.gz to ../dataset\MNIST\raw


180.4%

Extracting ../dataset\MNIST\raw\t10k-labels-idx1-ubyte.gz to ../dataset\MNIST\raw
Processing...
Done!


Dataset MNIST
    Number of datapoints: 60000
    Root location: ../dataset
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.1307,), std=(0.3081,))
           )

In [5]:
torch.manual_seed(seed)

use_cuda = not no_cuda and torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")

kwargs = {'num_workers': 1, 'pin_memory': True} if use_cuda else {}
#kwargs란?


train_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=True, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
    batch_size=batch_size, shuffle=True, **kwargs)




test_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=False, transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
    batch_size=test_batch_size, shuffle=True, **kwargs)

100.1%

Extracting ../data\MNIST\raw\train-images-idx3-ubyte.gz to ../data\MNIST\raw


113.5%

Extracting ../data\MNIST\raw\train-labels-idx1-ubyte.gz to ../data\MNIST\raw


100.4%

Extracting ../data\MNIST\raw\t10k-images-idx3-ubyte.gz to ../data\MNIST\raw


180.4%

Extracting ../data\MNIST\raw\t10k-labels-idx1-ubyte.gz to ../data\MNIST\raw
Processing...
Done!


# Optimization

In [6]:
model = Net().to(device) #모델을 Net()으로할 수 있는데 Cuda이므로, device로 넘김
optimizer = optim.SGD(model.parameters(), lr=lr, momentum=momentum)

In [7]:
params = list(model.parameters())

In [8]:
for i in range(8):
    print(params[i].size())
    # 파라미터 사이즈 확인

torch.Size([20, 1, 5, 5])
torch.Size([20])
torch.Size([50, 20, 5, 5])
torch.Size([50])
torch.Size([500, 800])
torch.Size([500])
torch.Size([10, 500])
torch.Size([10])


# Training

In [9]:
for epoch in range(1, epochs + 1):
    # Train Mode
    model.train()

    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()  # backpropagation 계산하기 전에 0으로 기울기 계산
        output = model(data)
        loss = F.nll_loss(output, target)  # https://pytorch.org/docs/stable/nn.html#nll-loss
        loss.backward()  # 계산한 기울기를 
        optimizer.step()  

        if batch_idx % log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.item()))
    

Train Epoch: 1 [0/60000 (0%)]	Loss: 2.300039
Train Epoch: 1 [6400/60000 (11%)]	Loss: 2.239658
Train Epoch: 1 [12800/60000 (21%)]	Loss: 2.133953
Train Epoch: 1 [19200/60000 (32%)]	Loss: 2.007282
Train Epoch: 1 [25600/60000 (43%)]	Loss: 1.656327
Train Epoch: 1 [32000/60000 (53%)]	Loss: 1.400292
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.864201
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.613135
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.615121
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.427839


# Evaluation

- 앞에서 model.train() 모드로 변한 것처럼 평가 할 때는 model.eval()로 설정
    - Batch Normalization이나 Drop Out 같은 Layer들을 잠금

In [10]:
# Test mode
model.eval()  # batch norm이나 dropout 등을 train mode 변환
# 모델의 가중치업데이트를 잠금.

Net(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=800, out_features=500, bias=True)
  (fc2): Linear(in_features=500, out_features=10, bias=True)
)

- autograd engine, 즉 backpropagatin이나 gradient 계산 등을 꺼서 memory usage를 줄이고 속도를 높임

In [14]:
# 뒤에서 설명
test_loss = 0
correct = 0  

with torch.no_grad(): #test시에는 grad끔
    data, target = next(iter(test_loader))
    data, target = data.to(device), target.to(device)
    output = model(data)
    
    # Model에서 나온 결과의 Loss를 계산하여 test_loss에 더함
    test_loss += F.nll_loss(output, target, reduction='sum').item()
    ## reduction=sum: output,target과의 차이를더하기
    
    pred = output.argmax(dim=1, keepdim=True) #차원수 유지
    #pred는 output중에 제일 큰 값을 갖는 index를 반환한다.
    correct += pred.eq(target.view_as(pred)).sum().item()  # pred와 target과 같은지 확인
    # target.view_as(pred)는 target과 pred를 비교해, 정답이 같으면 true, 아니면 false리턴.
    # 그 후 true의 갯수를 총 더함. 모든 iteration 후에 결과값을 평균하면 accuracy가 됨.

In [22]:
print(output.shape)
print(pred, pred.shape)
print(target, target.shape)
print(pred.eq(target.view_as(pred)))

torch.Size([16, 10])
tensor([[6],
        [6],
        [2],
        [3],
        [4],
        [3],
        [6],
        [1],
        [5],
        [3],
        [6],
        [0],
        [4],
        [8],
        [8],
        [9]], device='cuda:0') torch.Size([16, 1])
tensor([6, 6, 2, 7, 9, 3, 6, 1, 5, 8, 6, 0, 4, 7, 8, 4], device='cuda:0') torch.Size([16])
tensor([[ True],
        [ True],
        [ True],
        [False],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [False]], device='cuda:0')


In [24]:
test_loss

4.821728107452393e-05

In [25]:
# 앞에서 얻은 test_loss의 값을 test datset의 갯수로 나눠 평균값을 얻음
test_loss /= len(test_loader.dataset)

# test_loss, correct의 Log 확인
print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
    test_loss, correct, len(test_loader.dataset),
    100. * correct / len(test_loader.dataset)))


Test set: Average loss: 0.0000, Accuracy: 8652/10000 (87%)



In [26]:
# Test mode
model.eval()  # batch norm이나 dropout 등을 train mode 변환
test_loss = 0
correct = 0
with torch.no_grad():  # autograd engine, 즉 backpropagatin이나 gradient 계산 등을 꺼서 memory usage를 줄이고 속도를 높임
    for data, target in test_loader:
        data, target = data.to(device), target.to(device)
        output = model(data)
        test_loss += F.nll_loss(output, target, reduction='sum').item() # sum up batch loss
        
        pred = output.argmax(dim=1, keepdim=True) # get the index of the max log-probability
        
        correct += pred.eq(target.view_as(pred)).sum().item()  # pred와 target과 같은지 확인

test_loss /= len(test_loader.dataset)

print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
    test_loss, correct, len(test_loader.dataset),
    100. * correct / len(test_loader.dataset)))


Test set: Average loss: 0.4822, Accuracy: 8652/10000 (87%)

